version: "3.8"
services:
  configserver:
    image: santanubarua/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - bank-application-network

  account:
    image: santanubarua/account:latest
    ports:
      - "8080:8080"
    networks:
      - bank-application-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: configserver:http://configserver:8071/

  loan:
    image: santanubarua/loan:latest
    ports:
      - "8090:8090"
    networks:
      - bank-application-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: configserver:http://configserver:8071/


  card:
    image: santanubarua/card:latest
    ports:
      - "9000:9000"
    networks:
      - bank-application-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: configserver:http://configserver:8071/
networks:
  bank-application-network: